x

diff --git a/vps_knock b/vps_knock
--- a/vps_knock
+++ b/vps_knock
@@ -1,3 +1,14 @@
 #!/bin/sh
 
-~/vps_knock
+if [ "$1" == "" ]; then
+    echo "$0 <name>"
+    exit 1
+fi;
+
+IP=`cat ~/ip_$1.txt`
+if [ "$?" != "0" ]; then
+    echo "error: cat ~/ip_$1.txt"
+    exit 1
+fi;
+
+~/vps_knock $IP
diff --git a/vps_rsync_from b/vps_rsync_from
--- a/vps_rsync_from
+++ b/vps_rsync_from
@@ -1,6 +1,14 @@
 #!/bin/sh
 
-IP=`cat ~/ip_vps.txt`
+if [ "$1" == "" ]; then
+    echo "$0 <name>"
+    exit 1
+fi;
 
-vps_knock
-rsync -lvrP root@${IP}:~/vps/ ./
+IP=`cat ~/ip_$1.txt`
+if [ "$?" != "0" ]; then
+    echo "error: cat ~/ip_$1.txt"
+    exit 1
+fi;
+
+rsync -lvrP --exclude '.git' root@${IP}:~/vps/ ~/r/vps/
diff --git a/vps_ssh b/vps_ssh
--- a/vps_ssh
+++ b/vps_ssh
@@ -1,5 +1,14 @@
 #!/bin/sh
 
-vps_knock
+if [ "$1" == "" ]; then
+    echo "$0 <name>"
+    exit 1
+fi;
 
-ssh root@`cat ~/ip_vps.txt`
+IP=`cat ~/ip_$1.txt`
+if [ "$?" != "0" ]; then
+    echo "error: cat ~/ip_$1.txt"
+    exit 1
+fi;
+
+ssh root@${IP}
